
jenkins-master:
  build: jenkins-master
  ports:
    - 50000:50000
  volumes:
    - jenkins_home:/var/jenkins_home
    - jenkins-log:/var/log/jenkins
jenkins-nginx:
  build: jenkins-nginx
  ports:
    - 80:80
  links:
    - jenkins-master:jenkins-master


